# Generated by Django 5.2.9 on 2026-01-10 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('borrow', '借出'), ('return', '归还'), ('maintenance', '维护'), ('repair', '维修'), ('discard', '报废'), ('other', '其他')], max_length=20, verbose_name='操作类型')),
                ('operation_date', models.DateTimeField(verbose_name='操作日期')),
                ('description', models.TextField(blank=True, null=True, verbose_name='操作描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device', verbose_name='设备')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作员')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userinfo', verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '设备台账',
                'verbose_name_plural': '设备台账',
                'ordering': ['-operation_date'],
            },
        ),
    ]
