# Generated by Django 5.2.9 on 2026-01-10 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceledger',
            name='actual_return_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='实际归还时间'),
        ),
        migrations.AddField(
            model_name='deviceledger',
            name='device_name',
            field=models.CharField(default='', help_text='操作时的设备名称快照', max_length=100, verbose_name='设备名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deviceledger',
            name='expected_return_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='预期归还时间'),
        ),
        migrations.AddField(
            model_name='deviceledger',
            name='status_after_operation',
            field=models.CharField(choices=[('available', '可用'), ('unavailable', '不可用'), ('maintenance', '维修中'), ('discarded', '已报废')], default='available', max_length=20, verbose_name='操作后设备状态'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deviceledger',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userinfo', verbose_name='操作用户/借用人'),
        ),
    ]
