# Generated by Django 5.2.9 on 2026-01-10 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_alter_deviceledger_operator'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceledger',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.userinfo', verbose_name='操作用户/借用人'),
        ),
    ]
