# Generated by Django 5.2.9 on 2026-01-10 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('ledger', '0004_alter_deviceledger_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceledger',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.device', verbose_name='设备'),
        ),
    ]
