# Generated by Django 5.2.9 on 2026-01-10 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('week', '周报表'), ('month', '月报表'), ('year', '年报表')], max_length=10, verbose_name='报表类型')),
                ('report_name', models.CharField(max_length=200, verbose_name='报表名称')),
                ('start_date', models.DateField(verbose_name='统计开始日期')),
                ('end_date', models.DateField(verbose_name='统计结束日期')),
                ('report_data', models.JSONField(default=dict, verbose_name='报表数据')),
                ('total_bookings', models.IntegerField(default=0, verbose_name='总预约次数')),
                ('total_devices', models.IntegerField(default=0, verbose_name='设备总数')),
                ('total_users', models.IntegerField(default=0, verbose_name='用户总数')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总收入（元）')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('file_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='文件路径')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='生成人')),
            ],
            options={
                'verbose_name': '报表',
                'verbose_name_plural': '报表管理',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['report_type', 'start_date', 'end_date'], name='labadmin_re_report__9a8bf0_idx'), models.Index(fields=['generated_at'], name='labadmin_re_generat_b6079b_idx')],
            },
        ),
    ]
