# Generated by Django 5.2.9 on 2026-01-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('week', '周报表'), ('month', '月报表'), ('year', '年报表'), ('custom', '自定义时间段报表')], max_length=10, verbose_name='报表类型'),
        ),
    ]
